version: "3.9"
services:
  orchestrator:
    build: ./cmd/orchestrator
    ports:
      - "8080:8080"

  fl-aggregator:
    build: ./cmd/fl-aggregator
    ports:
      - "8090:8090"

  node-agent-1:
    build: ./cmd/node-agent
    depends_on:
      - orchestrator
      - fl-aggregator
