global:
  scrape_interval: 15s

scrape_configs:
  - job_name: orchestrator
    metrics_path: /metrics
    static_configs:
      - targets: ["orchestrator:9091"]

  - job_name: tpm-metrics
    metrics_path: /metrics
    static_configs:
      - targets: ["tpm-metrics:9102"]