#!/usr/bin/env python3
"""Build TPM production sign-off artifacts from platform result rows."""

from __future__ import annotations

import argparse
import datetime as dt
import json
from pathlib import Path

REQUIRED_PLATFORMS = ("linux", "windows", "macos")


def _load_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def _write_json(path: Path, payload: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def _render_matrix_markdown(matrix: dict) -> str:
    lines = [
        "# TPM Attestation Cross-Platform Matrix",
        "",
        f"- Generated (UTC): `{matrix['generated_utc']}`",
        "",
        "| Platform | Status | Evidence Count |",
        "| --- | --- | ---: |",
    ]
    for row in matrix.get("platforms", []):
        evidence = row.get("evidence", [])
        evidence_count = len(evidence) if isinstance(evidence, list) else 0
        lines.append(
            f"| {row.get('platform', 'unknown')} | {row.get('status', 'missing')} | {evidence_count} |"
        )
    lines.append("")
    return "\n".join(lines)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Build TPM sign-off matrix and attestation artifacts."
    )
    parser.add_argument(
        "--rows-dir",
        default="test-results/tpm-signoff/rows",
        help="Directory containing per-platform row JSON files.",
    )
    parser.add_argument(
        "--date-stamp",
        default=dt.datetime.now(dt.timezone.utc).strftime("%Y-%m-%d"),
        help="Date stamp suffix for generated artifacts (YYYY-MM-DD).",
    )
    parser.add_argument(
        "--evidence-dir",
        default="results/go-live/evidence",
        help="Directory for generated evidence artifacts.",
    )
    parser.add_argument(
        "--attestation-file",
        default="results/go-live/attestations/tpm_attestation_production_closure.json",
        help="Path for production closure attestation JSON.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    repo_root = Path(__file__).resolve().parents[1]

    rows_dir = repo_root / args.rows_dir
    evidence_dir = repo_root / args.evidence_dir
    attestation_path = repo_root / args.attestation_file

    rows_by_platform: dict[str, dict] = {}
    # Support both flattened and per-artifact directory layouts.
    row_files = sorted(rows_dir.rglob("row.json"))
    if not row_files:
        row_files = sorted(rows_dir.glob("*.json"))

    for row_file in row_files:
        row = _load_json(row_file)
        platform = str(row.get("platform", "")).strip().lower()
        if platform:
            rows_by_platform[platform] = row

    matrix_rows = []
    all_pass = True
    for platform in REQUIRED_PLATFORMS:
        row = rows_by_platform.get(platform)
        if row is None:
            matrix_rows.append(
                {
                    "platform": platform,
                    "status": "missing",
                    "evidence": [],
                    "notes": "missing platform result row",
                }
            )
            all_pass = False
            continue

        status = str(row.get("status", "missing")).strip().lower()
        if status != "pass":
            all_pass = False
        matrix_rows.append(
            {
                "platform": platform,
                "status": status,
                "evidence": row.get("evidence", []),
                "runner": row.get("runner", "unknown"),
                "go_version": row.get("go_version", "unknown"),
                "generated_utc": row.get("generated_utc", "unknown"),
            }
        )

    generated_utc = dt.datetime.now(dt.timezone.utc).replace(microsecond=0).isoformat()
    matrix = {
        "generated_utc": generated_utc,
        "platforms": matrix_rows,
        "required_platforms": list(REQUIRED_PLATFORMS),
        "all_platforms_pass": all_pass,
    }

    matrix_json = evidence_dir / f"tpm_attestation_cross_platform_matrix_{args.date_stamp}.json"
    matrix_md = evidence_dir / f"tpm_attestation_cross_platform_matrix_{args.date_stamp}.md"
    _write_json(matrix_json, matrix)
    matrix_md.parent.mkdir(parents=True, exist_ok=True)
    matrix_md.write_text(_render_matrix_markdown(matrix), encoding="utf-8")

    attestation = {
        "status": "approved" if all_pass else "blocked",
        "control": "tpm_attestation_production_closure",
        "generated_utc": generated_utc,
        "evidence": [
            str(matrix_json.relative_to(repo_root)).replace("\\", "/"),
            str(matrix_md.relative_to(repo_root)).replace("\\", "/"),
        ],
        "notes": "Generated by TPM production sign-off workflow.",
    }
    _write_json(attestation_path, attestation)

    print(f"wrote {matrix_json}")
    print(f"wrote {matrix_md}")
    print(f"wrote {attestation_path}")
    print(f"all_platforms_pass={str(all_pass).lower()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
