#!/bin/bash
# Interactive development environment configuration
# Status: PHASE 1 - CRITICAL FIXES
# Purpose: Walk users through setup with clear prompts

set -e

echo "🔧 Sovereign-Mohawk Development Environment Configuration"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Create config file
ENV_FILE=".env.local"

echo "This wizard will help you configure your development environment."
echo "Configuration will be saved to: $ENV_FILE"
echo ""

# TPM Configuration
echo "▸ TPM Configuration"
read -p "  TPM Client Certificate Pool Size (default: 128): " TPM_SIZE
TPM_SIZE=${TPM_SIZE:-128}
echo ""

# API Configuration
echo "▸ API Server Configuration"
read -p "  API Listen Port (default: 8080): " API_PORT
API_PORT=${API_PORT:-8080}
read -p "  API Metrics Port (default: 8081): " API_METRICS_PORT
API_METRICS_PORT=${API_METRICS_PORT:-8081}
echo ""

# Node Configuration
echo "▸ Node Configuration"
read -p "  Node ID (default: dev-node-1): " NODE_ID
NODE_ID=${NODE_ID:-dev-node-1}
read -p "  Node Listen Port (default: 9080): " NODE_PORT
NODE_PORT=${NODE_PORT:-9080}
echo ""

# Orchestrator Configuration
echo "▸ Orchestrator Configuration"
read -p "  Orchestrator Listen Port (default: 8090): " ORCH_PORT
ORCH_PORT=${ORCH_PORT:-8090}
echo ""

# Metrics Configuration
echo "▸ Metrics Configuration"
read -p "  Metrics Exporter Port (default: 9090): " METRICS_PORT
METRICS_PORT=${METRICS_PORT:-9090}
echo ""

# Debug Configuration
echo "▸ Debug Configuration"
read -p "  Enable debug mode? (default: yes) [y/n]: " DEBUG_MODE
DEBUG_MODE=${DEBUG_MODE:-y}
if [ "$DEBUG_MODE" = "y" ]; then
    DEBUG=true
    RUST_LOG=debug
else
    DEBUG=false
    RUST_LOG=info
fi
echo ""

# Write configuration file
cat > "$ENV_FILE" << EOF
# Sovereign-Mohawk Development Environment Configuration
# Auto-generated by configure-dev-env.sh

# TPM Configuration
MOHAWK_TPM_CLIENT_CERT_POOL_SIZE=$TPM_SIZE

# API Configuration
MOHAWK_API_LISTEN_PORT=$API_PORT
MOHAWK_API_METRICS_PORT=$API_METRICS_PORT

# Node Configuration
MOHAWK_NODE_ID=$NODE_ID
MOHAWK_NODE_LISTEN_PORT=$NODE_PORT

# Metrics Exporter Configuration
MOHAWK_METRICS_LISTEN_PORT=$METRICS_PORT

# Orchestrator Configuration
MOHAWK_ORCHESTRATOR_LISTEN_PORT=$ORCH_PORT

# Development flags
DEBUG=$DEBUG
RUST_LOG=$RUST_LOG
EOF

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✓ Configuration saved to: $ENV_FILE"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📝 Configuration Summary:"
echo "   API Port:           $API_PORT"
echo "   Node ID:            $NODE_ID"
echo "   Orchestrator Port:  $ORCH_PORT"
echo "   Debug Mode:         $DEBUG"
echo ""
echo "💡 To use this configuration, copy to .env:"
echo "   cp $ENV_FILE .env"
echo ""
