#!/usr/bin/env python3
import datetime as dt
from pathlib import Path

CANONICAL_OUTPUT = Path("results/metrics/release_performance_evidence.md")
MIRROR_OUTPUT = Path("captured_artifacts/release_performance_evidence.md")

SECTIONS = [
    (
        "Bridge Compression",
        Path("results/metrics/bridge_compression_benchmark_compare.md"),
        "JSON vs zero-copy compression benchmark.",
        False,
    ),
    (
        "FedAvg Matrix",
        Path("results/metrics/fedavg_benchmark_compare.md"),
        "Worker and workload matrix comparison for aggregation throughput.",
        False,
    ),
    (
        "SDK Benchmarks",
        Path("benchmark-results.json"),
        "Python SDK benchmark JSON generated by performance gate (optional local artifact).",
        True,
    ),
]


def build_report(repo_root: Path) -> str:
    generated_utc = dt.datetime.now(dt.timezone.utc).replace(microsecond=0).isoformat()
    lines = [
        "# Release Performance Evidence",
        "",
        f"Generated (UTC): `{generated_utc}`",
        "",
        "This index summarizes performance evidence used for release sign-off.",
        "",
        "| Area | Artifact | Status | Notes |",
        "| --- | --- | --- | --- |",
    ]

    for area, rel_path, note, optional in SECTIONS:
        abs_path = repo_root / rel_path
        if abs_path.exists():
            status = "present"
            artifact = f"`{rel_path.as_posix()}`"
        else:
            status = "external-artifact" if optional else "missing"
            artifact = f"`{rel_path.as_posix()}`"
        lines.append(f"| {area} | {artifact} | {status} | {note} |")

    lines.extend(
        [
            "",
            "## Sign-off Guidance",
            "",
            "- Require all non-optional artifacts to be present for release-candidate sign-off.",
            "- Treat `external-artifact` status as satisfied when the corresponding CI artifact is attached.",
            "- Re-run bridge and FedAvg benchmark scripts after aggregation or bridge serialization changes.",
            "- Attach this file to release notes and go-live evidence packages.",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    repo_root = Path(__file__).resolve().parents[1]
    report = build_report(repo_root)

    canonical_output = repo_root / CANONICAL_OUTPUT
    canonical_output.parent.mkdir(parents=True, exist_ok=True)
    canonical_output.write_text(report, encoding="utf-8")

    mirror_output = repo_root / MIRROR_OUTPUT
    mirror_output.parent.mkdir(parents=True, exist_ok=True)
    mirror_output.write_text(report, encoding="utf-8")

    print(f"wrote release evidence index to {canonical_output}")
    print(f"mirrored release evidence index to {mirror_output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
