#!/bin/bash
# Quick-start development environment setup
# Status: PHASE 1 - CRITICAL FIXES
# Purpose: One-command setup, 5 minutes to full stack

set -e

echo "🚀 Starting Sovereign-Mohawk Quick-Start Setup..."
echo ""

# Step 1: Validate environment
echo "Step 1: Validating prerequisites..."
if [ -f "scripts/validate-dev-environment.sh" ]; then
    bash scripts/validate-dev-environment.sh || exit 1
fi
echo ""

# Step 2: Create .env if missing
echo "Step 2: Configuring environment..."
if [ ! -f ".env" ]; then
    echo "Creating .env file with defaults..."
    cat > .env << 'EOF'
# Sovereign-Mohawk Development Environment Configuration
# Auto-generated by quick-start-dev.sh

# TPM Configuration
MOHAWK_TPM_CLIENT_CERT_POOL_SIZE=128

# API Configuration
MOHAWK_API_LISTEN_PORT=8080
MOHAWK_API_METRICS_PORT=8081

# Node Configuration
MOHAWK_NODE_ID=dev-node-1
MOHAWK_NODE_LISTEN_PORT=9080

# Metrics Exporter Configuration
MOHAWK_METRICS_LISTEN_PORT=9090

# Orchestrator Configuration
MOHAWK_ORCHESTRATOR_LISTEN_PORT=8090

# Development flags
DEBUG=true
RUST_LOG=debug
EOF
    echo "✓ Created .env file"
else
    echo "✓ .env file already exists"
fi
echo ""

# Step 3: Start core services with profiles
echo "Step 3: Starting core services..."
echo "   - Runtime secrets initialization"
echo "   - Orchestrator"
echo "   - API server"
echo ""

if command -v docker-compose &> /dev/null; then
    COMPOSE_CMD="docker-compose"
elif command -v docker &> /dev/null; then
    COMPOSE_CMD="docker compose"
else
    echo "❌ Docker Compose not found"
    exit 1
fi

$COMPOSE_CMD up -d runtime-secrets-init orchestrator api 2>&1 | grep -v "service provisioning" || true

echo ""
echo "Step 4: Waiting for services to be ready..."
sleep 3

# Step 5: Verify services
echo "Step 5: Verifying services..."
$COMPOSE_CMD ps

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✓ Quick-start complete!"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📝 Next steps:"
echo "   1. View logs:      docker-compose logs -f orchestrator"
echo "   2. Check status:   make status"
echo "   3. Run tests:      docker-compose exec orchestrator go test ./..."
echo "   4. Stop services:  docker-compose down"
echo ""
echo "📚 Documentation:     docs/README.md"
echo ""
